openapi: "3.0.0"
info:
  title: "Wutsi Payment API"
  description: |
    API for managing payments.
    This API allows to
    - Cash in: Move money from owner's account into the wallet
    - Cash out: Move monet from wallet to owner's account
    - Transfer: Transfer money between wallets
  version: "1.0.0"

servers:
  - url: https://wutsi-payment-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-payment-server-prod.herokuapp.com
    description: Production

paths:
  /v1/transactions/cashins:
    post:
      operationId: "create-cashin"
      description: Add money into the wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCashinRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCashinResponse'
        409:
          description: The operation failed
      tags:
        - Transactions
      security:
        - api_key: [ 'payment-manage' ]

  /v1/transactions/transfers:
    post:
      operationId: "create-transfer"
      description: Transfer money to another user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransferRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransferResponse'
        409:
          description: The operation failed
      tags:
        - Transactions
      security:
        - api_key: [ 'payment-manage' ]

  /v1/accounts/{user-id}/balance:
    get:
      operationId: "get-balance"
      description: Get balance of a user
      parameters:
        - in: path
          name: user-id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBalanceResponse'
      tags:
        - Account
      security:
        - api_key: [ 'payment-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateCashinRequest:
      type: object
      properties:
        paymentMethodToken:
          type: string
          description: Token of the payment method from where the money will be transfered from.
        amount:
          type: number
          format: double
          description: Amout to transfer to the user's wallet
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
      required:
        - paymentMethodToken
        - currency

    CreateCashinResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the transaction
        status:
          description: Status of the charge
          type: string
          enum:
            - PENDING
            - SUCESS

    CreateTransferRequest:
      type: object
      properties:
        recipientId:
          type: integer
          format: int64
          description: ID of the recipient of the transfer
        amount:
          type: number
          format: double
          description: Amout to transfer to the user's wallet
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
        description:
          type: string
          description: Description of the transfer
          nullable: true
      required:
        - currency

    CreateTransferResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the transaction
        status:
          description: Status of the charge
          type: string
          enum:
            - PENDING
            - SUCESS


    Balance:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the account
        userId:
          type: integer
          format: int64
          description: ID of the user who owns this balance
        tenantId:
          type: integer
          format: int64
          description: ID of the tenant
        amount:
          type: number
          format: double
          description: Balance of the account
        currency:
          type: string
          description: 3 letter currency code
        created:
          type: string
          description: Creation data-time
          format: date-time
        updated:
          type: string
          description: Date/Time of the last updated
          format: date-time

    GetBalanceResponse:
      type: object
      properties:
        balance:
          type: object
          $ref: "#/components/schemas/Balance"
