openapi: "3.0.0"
info:
  title: "Wutsi Security Server"
  description: |
    Wutsi Security Server. It provides the following features:

    - [JWT](https://jwt.io) authentication
    - Application registration
  version: "1.0.0"

servers:
  - url: https://wutsi-auth-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-auth-server-prod.herokuapp.com
    description: Production

paths:
  /v1/keys:
    get:
      operationId: "get-key"
      description: |
        Return the server's key. This key can be used for decrypting message for verifying signatures
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetKeyResponse'
      tags:
        - Security

    post:
      operationId: "create-key"
      description: |
        Create the server's key
      responses:
        201:
          description: Success
      tags:
        - Security


components:
  schemas:
    GetKeyResponse:
      type: object
      properties:
        key:
          type: object
          $ref: "#/components/schemas/Key"

    Key:
      type: object
      properties:
        algorithm:
          type: string
        content:
          type: string
