openapi: "3.0.0"
info:
  title: "Wutsi Order API"
  description: |
    API for managing orders. Order are created by merchants so that they can receive payments.
  version: "1.0.0"

servers:
  - url: https://wutsi-order-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-order-server-prod.herokuapp.com
    description: Production

paths:
  /v1/orders:
    post:
      operationId: "create-order"
      description: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        409:
          description: The operation failed
      tags:
        - Orders
      security:
        - api_key: [ 'order-manage' ]

  /v1/orders/{id}:
    get:
      operationId: "get-order"
      description: Return an order
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
        404:
          description: Order not found
      tags:
        - Orders
      security:
        - api_key: [ 'order-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateOrderRequest:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          description: Merchant Identififier
        invoiceId:
          type: string
          description: ID of the invoice
          nullable: true
        description:
          type: string
          description: Description of the order
          nullable: true
        amount:
          type: number
          format: double
          description: Amount of the order
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
      required:
        - currency

    CreateOrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the Order

    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the Order
        tenantId:
          type: integer
          format: int64
          description: ID of the Tenant
        deviceId:
          type: string
          description: ID of the device from where the order come from
        accountId:
          type: integer
          format: int64
          description: Merchant account Id
        invoiceId:
          type: string
          description: ID of the invoice
          nullable: true
        description:
          type: string
          description: Description of the order
          nullable: true
        amount:
          type: number
          format: double
          description: Amount of the order
        currency:
          type: string
          description: 3 letter currency code

    GetOrderResponse:
      type: object
      properties:
        transaction:
          type: object
          $ref: "#/components/schemas/Order"
